spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/communist?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath\:/META-INF/resources/,classpath\:/resources/,classpath\:/static/


