spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/communist?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

#自定义变量
ImageUrl: http://localhost:8080/PersonImage/
ImageResources: file:/home/icesource/项目/党员管理系统/communist-server/src/main/resources/PersonImage/
ImageLocation: ./src/main/resources/PersonImage/

NewsImageUrl: http://localhost:8080/NewsImage/
NewsImageResources: file:/home/icesource/项目/党员管理系统/communist-server/src/main/resources/NewsImage/
NewsImageLocation: ./src/main/resources/NewsImage/

HomepageImage: HomepageImage/
HomepageImageResources: file:/home/icesource/项目/党员管理系统/communist-server/src/main/resources/NewsImage/HomepageImage/
