spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/communist?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

#自定义变量
ImageUrl: http://localhost:8080/image/
ImageResources: file:/home/icesource/IdeaProjects/communist/src/main/resources/photo/
ImageLocation: ./src/main/resources/photo/

NewsImageUrl: http://localhost:8080/NewsImage/
NewsImageResources: file:/home/icesource/IdeaProjects/communist/src/main/resources/photo/NewsImage/
NewsImageLocation: ./src/main/resources/NewsImage/

