spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/communist?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

#自定义变量
PersonImageUrl: http://localhost:8080/PersonImage/
PersonImageResources: file:C://Users/10049/Desktop/item/demo/src/main/resources/PersonImage/
PersonImageLocation: ./src/main/resources/PersonImage/

NewsImageUrl: http://localhost:8080/NewsImage/
NewsImageResources: file:C://Users/10049/Desktop/item/demo/src/main/resources/NewsImage/
NewsImageLocation: ./src/main/resources/NewsImage/

HomepageImageUrl: http://localhost:8080/NewsImage/HomepageImage/
HomepageImageResources: file:C://Users/10049/Desktop/item/demo/src/main/resources/NewsImage/HomepageImage/
HomepageImageLocation: ./src/main/resources/NewsImage/HomepageImage/
